export const sectorRanges = [
  { sector: "Calle A", start: 0, end: 107, street: true },
  { sector: "Calle B", start: 108, end: 209, street: true },
  { sector: "Calle C", start: 210, end: 303, street: true },
  { sector: "Calle D", start: 304, end: 389, street: true },
  { sector: "Calle E", start: 390, end: 468, street: true },
  { sector: "Calle F", start: 469, end: 540, street: true },
  { sector: "Calle G", start: 541, end: 603, street: true },
  { sector: "Calle H", start: 604, end: 657, street: true },
  { sector: "Calle I", start: 658, end: 705, street: true },
  { sector: "Sector Rojo", start: 1, end: 164 },
  { sector: "Calle Nueva", start: 1, end: 40 },
  { sector: "Sector Comidas", start: 1, end: 60 },
  { sector: "Sector Usado", start: 1, end: 200 },
  { sector: "Peluquerias", start: 1, end: 20 },
];

export const sectors = sectorRanges.map((range) => range.sector);

export const rubros = [
  "Ropa",
  "Moda femenina",
  "Moda masculina",
  "Moda infantil",
  "Calzado",
  "Zapatillas",
  "Marroquineria",
  "Accesorios",
  "Bijouterie",
  "Perfumeria",
  "Cosmetica",
  "Deportes",
  "Bazar",
  "Hogar",
  "Decoracion",
  "Jugueteria",
  "Libreria",
  "Electronica",
  "Celulares",
  "Informatica",
  "Herramientas",
  "Ferreteria",
  "Autopartes",
  "Repuestos",
  "Multirubro",
  "Alimentos",
  "Bebidas",
  "Panificados",
  "Golosinas",
  "Verduleria",
  "Comidas rapidas",
  "Parrilla",
  "Peluqueria",
  "Estetica",
  "Artesanias",
  "Regaleria",
  "Plantas",
  "Mascotas",
  "Usado",
  "Antiguedades",
];

export const carBrands = [
  "Audi",
  "BMW",
  "Chevrolet",
  "Chery",
  "Citroen",
  "Fiat",
  "Ford",
  "Honda",
  "Hyundai",
  "Jeep",
  "Kia",
  "Mercedes-Benz",
  "Mitsubishi",
  "Nissan",
  "Peugeot",
  "Renault",
  "Toyota",
  "Volkswagen",
  "Volvo",
];

export const carColors = [
  "Amarillo",
  "Azul",
  "Beige",
  "Blanco",
  "Bordo",
  "Celeste",
  "Champagne",
  "Dorado",
  "Gris",
  "Marron",
  "Naranja",
  "Negro",
  "Plateado",
  "Rojo",
  "Rosa",
  "Verde",
  "Violeta",
];

export const navItems = [
  ["dashboard", "Panel"],
  ["puestos", "Gestion de puestos"],
  ["cobranza", "Cobranza"],
  ["gastos", "Gastos"],
  ["playa", "Playa de autos"],
  ["estadisticas", "Estadisticas"],
];

export const users = [
  { username: "ENTRADA 1", password: "1234", role: "entrada", allowedViews: ["playa"] },
  { username: "ENTRADA 2", password: "1234", role: "entrada", allowedViews: ["playa"] },
  { username: "ENTRADA 3", password: "1234", role: "entrada", allowedViews: ["playa"] },
  { username: "ENTRADA 4", password: "1234", role: "entrada", allowedViews: ["playa"] },
  { username: "GUSTAVO", password: "Admin123", role: "maestro", allowedViews: navItems.map(([id]) => id) },
];
